USE CSE_3B_435
 CREATE TABLE BRANCH(
 BNAME VARCHAR(50),
 CITY VARCHAR(50),
 )
INSERT INTO BRANCH VALUES('VRACE','NAGPUR')
INSERT INTO BRANCH VALUES('AJNI','NAGPUR')
INSERT INTO BRANCH VALUES('KAROLBAGH','NAGPUR')
INSERT INTO BRANCH VALUES('CHANDI','NAGPUR')
INSERT INTO BRANCH VALUES('DHARAMPETH','NAGPUR')
INSERT INTO BRANCH VALUES('M.G. ROAD','NAGPUR')
INSERT INTO BRANCH VALUES('ANDHERI','NAGPUR')
INSERT INTO BRANCH VALUES('VIRAR','NAGPUR')
INSERT INTO BRANCH VALUES('NEHRU PLACE  ','NAGPUR')
INSERT INTO BRANCH VALUES('POWAI','NAGPUR')
