USE CSE_3B_435
CREATE TABLE CUSTOMERS(
CNAME VARCHAR(50),
CITY VARCHAR(50)
)
INSERT INTO CUSTOMERS VALUES ('ANIL','CALCUTTA')
INSERT INTO CUSTOMERS VALUES ('SUNIL','DELHI')
INSERT INTO CUSTOMERS VALUES ('MEHUL','BARODA')
INSERT INTO CUSTOMERS VALUES ('MANDAR','PATNA')
INSERT INTO CUSTOMERS VALUES ('MADHURI','NAGPUR')
INSERT INTO CUSTOMERS VALUES ('PRAMOD','NAGPUR')
INSERT INTO CUSTOMERS VALUES ('SANDIP','SURAT')
INSERT INTO CUSTOMERS VALUES ('SHIVANI','BOMBAY')
INSERT INTO CUSTOMERS VALUES ('KRANTI','BOMBAY')
INSERT INTO CUSTOMERS VALUES ('NAREN','BOMBAY')